-- Run this script after connecting to the target PostgreSQL database.

-- Users Table (for Admin login)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    live_url VARCHAR(255),
    github_url VARCHAR(255),
    tech_stack JSONB, -- Store array of technologies as JSON
    featured BOOLEAN DEFAULT FALSE,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Skills Table
CREATE TABLE IF NOT EXISTS skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    proficiency INT CHECK (proficiency >= 0 AND proficiency <= 100),
    category VARCHAR(50) NOT NULL, -- e.g., 'Frontend', 'Backend'
    icon VARCHAR(255),
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contact Submissions Table
CREATE TABLE IF NOT EXISTS contact_submissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255),
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Experiences Table
CREATE TABLE IF NOT EXISTS experiences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    period VARCHAR(100), -- e.g., "Jan 2020 - Present"
    description JSONB, -- Array of bullet points
    technologies JSONB, -- Array of tech used
    is_current BOOLEAN DEFAULT FALSE,
    type VARCHAR(50), -- e.g., 'Full-time', 'Freelance'
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Profile Settings Table (Single row expected)
CREATE TABLE IF NOT EXISTS profile_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_title VARCHAR(255),
    hero_subtitle VARCHAR(255),
    hero_name VARCHAR(100),
    hero_bio TEXT,
    about_intro TEXT,
    about_description TEXT,
    avatar_url VARCHAR(255),
    resume_url VARCHAR(255),
    github_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    twitter_url VARCHAR(255),
    email VARCHAR(255),
    footer_copyright VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Certificates Table
CREATE TABLE IF NOT EXISTS certificates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    issue_date DATE,
    credential_url VARCHAR(255),
    image_url VARCHAR(255),
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Default admin user
-- Email: vikasjagtap.9996@gmail.com
-- Password: @Vikas123
-- The password is stored as a bcrypt hash, never as plain text.
INSERT INTO users (email, password_hash, role)
VALUES (
    'vikasjagtap.9996@gmail.com',
    '$2b$10$unQBaG0jC3Qm7CdZ3K5L7.BefGb9Y98lNKcwL76RIoOB6ffeMS78m',
    'admin'
)
ON CONFLICT (email) DO UPDATE SET role = EXCLUDED.role;

-- Starter portfolio data. These inserts are safe to run more than once.
INSERT INTO profile_settings (hero_title, hero_subtitle, hero_name, hero_bio, email)
SELECT 'Full Stack Developer', 'Building useful digital experiences', 'Vikas Jagtap',
       'B.Sc. Computer Science student and aspiring full stack developer.',
       'vikasjagtap.9996@gmail.com'
WHERE NOT EXISTS (SELECT 1 FROM profile_settings);

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'React', 85, 'Frontend', 1
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'React');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'Node.js', 80, 'Backend', 2
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'Node.js');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'MySQL', 75, 'Database', 3
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'MySQL');

INSERT INTO projects (title, description, tech_stack, featured, display_order)
SELECT 'Developer Portfolio', 'A production-ready personal portfolio website.',
    '["React", "TypeScript", "Node.js", "PostgreSQL"]'::jsonb, TRUE, 1
WHERE NOT EXISTS (SELECT 1 FROM projects WHERE title = 'Developer Portfolio');
