-- Run this script after connecting to the target PostgreSQL database.

-- Users Table (for Admin login)
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'user' CHECK (role IN ('admin', 'user')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    image_url VARCHAR(255),
    live_url VARCHAR(255),
    github_url VARCHAR(255),
    tech_stack JSONB, -- Store array of technologies as JSON
    featured BOOLEAN DEFAULT FALSE,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Skills Table
CREATE TABLE IF NOT EXISTS skills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    proficiency INT CHECK (proficiency >= 0 AND proficiency <= 100),
    category VARCHAR(50) NOT NULL, -- e.g., 'Frontend', 'Backend'
    icon VARCHAR(255),
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contact Submissions Table
CREATE TABLE IF NOT EXISTS contact_submissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    subject VARCHAR(255),
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Experiences Table
CREATE TABLE IF NOT EXISTS experiences (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    period VARCHAR(100), -- e.g., "Jan 2020 - Present"
    description JSONB, -- Array of bullet points
    technologies JSONB, -- Array of tech used
    is_current BOOLEAN DEFAULT FALSE,
    type VARCHAR(50), -- e.g., 'Full-time', 'Freelance'
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Profile Settings Table (Single row expected)
CREATE TABLE IF NOT EXISTS profile_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_title VARCHAR(255),
    hero_subtitle VARCHAR(255),
    hero_name VARCHAR(100),
    hero_bio TEXT,
    about_intro TEXT,
    about_description TEXT,
    avatar_url VARCHAR(255),
    resume_url VARCHAR(255),
    github_url VARCHAR(255),
    linkedin_url VARCHAR(255),
    twitter_url VARCHAR(255),
    email VARCHAR(255),
    footer_copyright VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Keep updated_at current for profile edits in PostgreSQL.
CREATE OR REPLACE FUNCTION update_profile_settings_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS profile_settings_updated_at ON profile_settings;
CREATE TRIGGER profile_settings_updated_at
BEFORE UPDATE ON profile_settings
FOR EACH ROW EXECUTE FUNCTION update_profile_settings_timestamp();

-- Additional profile fields used by the frontend.
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_primary VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_secondary VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_primary_college VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_primary_cgpa VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_primary_start VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_primary_end VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_secondary_college VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_secondary_cgpa VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_secondary_start VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_education_secondary_end VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS career_goals JSONB;
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS hero_background_url VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS about_image_url VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS stat_years_experience VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS stat_projects_completed VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS stat_technologies VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS stat_client_satisfaction VARCHAR(50);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS footer_tagline VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS footer_location VARCHAR(255);
ALTER TABLE profile_settings ADD COLUMN IF NOT EXISTS what_i_do JSONB;

-- Certificates Table
CREATE TABLE IF NOT EXISTS certificates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    issuer VARCHAR(255) NOT NULL,
    issue_date DATE,
    credential_url VARCHAR(255),
    image_url VARCHAR(255),
    display_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Notification settings (single row expected).
CREATE TABLE IF NOT EXISTS notification_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_email VARCHAR(255),
    send_confirmation_email BOOLEAN DEFAULT FALSE
);

-- Resume settings (single row expected).
CREATE TABLE IF NOT EXISTS resume_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_url VARCHAR(255),
    file_name VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Default admin user
-- Email: vikasjagtap.9996@gmail.com
-- Password: @Vikas123
-- The password is stored as a bcrypt hash, never as plain text.
INSERT INTO users (email, password_hash, role)
VALUES (
    'vikasjagtap.9996@gmail.com',
    '$2b$10$unQBaG0jC3Qm7CdZ3K5L7.BefGb9Y98lNKcwL76RIoOB6ffeMS78m',
    'admin'
)
ON CONFLICT (email) DO UPDATE SET role = EXCLUDED.role;

-- Starter portfolio data. These inserts are safe to run more than once.
INSERT INTO profile_settings (
    hero_title, hero_subtitle, hero_name, hero_bio, about_intro, about_description,
    email, github_url, linkedin_url, twitter_url, footer_copyright,
    about_education_primary, about_education_secondary, career_goals,
    stat_years_experience, stat_projects_completed, stat_technologies,
    stat_client_satisfaction, footer_tagline, footer_location, what_i_do
)
SELECT 'Full Stack Developer', 'Building useful digital experiences', 'Vikas Jagtap',
       'B.Sc. Computer Science student and aspiring full stack developer.',
       'I build clean, reliable web applications that solve real problems.',
       'I enjoy working across the stack, from accessible interfaces to dependable APIs and data models.',
       'vikasjagtap.9996@gmail.com',
       'https://github.com/vikasjagtap',
       'https://www.linkedin.com/in/vikas-jagtap',
       'https://twitter.com/vikasjagtap',
       '© 2026 Vikas Jagtap. All rights reserved.',
       'B.Sc. Computer Science', 'Maharashtra, India',
       '["Become a skilled full stack developer", "Build products that help people", "Keep learning modern technologies"]'::jsonb,
       '1+', '10+', '15+', '100%', 'Building useful digital experiences', 'Maharashtra, India',
       '[{"title":"Frontend Development","description":"Responsive and accessible interfaces with React and TypeScript."},{"title":"Backend Development","description":"Secure APIs and data-driven services with Node.js."},{"title":"Database Design","description":"Practical relational data models with PostgreSQL and SQL."}]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM profile_settings);

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'React', 85, 'Frontend', 1
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'React');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'Node.js', 80, 'Backend', 2
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'Node.js');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'MySQL', 75, 'Database', 3
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'MySQL');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'TypeScript', 80, 'Frontend', 4
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'TypeScript');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'JavaScript', 90, 'Frontend', 5
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'JavaScript');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'Express.js', 80, 'Backend', 6
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'Express.js');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'PostgreSQL', 75, 'Database', 7
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'PostgreSQL');

INSERT INTO skills (name, proficiency, category, display_order)
SELECT 'Git', 85, 'Tools', 8
WHERE NOT EXISTS (SELECT 1 FROM skills WHERE name = 'Git');

INSERT INTO projects (title, description, tech_stack, featured, display_order)
SELECT 'Developer Portfolio', 'A production-ready personal portfolio website.',
    '["React", "TypeScript", "Node.js", "PostgreSQL"]'::jsonb, TRUE, 1
WHERE NOT EXISTS (SELECT 1 FROM projects WHERE title = 'Developer Portfolio');

INSERT INTO projects (title, description, tech_stack, live_url, github_url, featured, display_order)
SELECT 'Task Management App', 'A focused task management application with authentication and responsive workflows.',
    '["React", "TypeScript", "Node.js", "PostgreSQL"]'::jsonb,
    'https://example.com/task-manager', 'https://github.com/vikasjagtap/task-manager', TRUE, 2
WHERE NOT EXISTS (SELECT 1 FROM projects WHERE title = 'Task Management App');

INSERT INTO projects (title, description, tech_stack, live_url, github_url, featured, display_order)
SELECT 'Weather Dashboard', 'A responsive dashboard that presents current weather and forecast information.',
    '["React", "JavaScript", "REST API", "CSS"]'::jsonb,
    'https://example.com/weather-dashboard', 'https://github.com/vikasjagtap/weather-dashboard', FALSE, 3
WHERE NOT EXISTS (SELECT 1 FROM projects WHERE title = 'Weather Dashboard');

INSERT INTO experiences (company, title, location, period, description, technologies, is_current, type, display_order)
SELECT 'Freelance', 'Full Stack Developer', 'Remote', '2025 - Present',
    '["Build responsive portfolio and business websites", "Design REST APIs and PostgreSQL data models", "Deploy and maintain production applications"]'::jsonb,
    '["React", "TypeScript", "Node.js", "Express", "PostgreSQL"]'::jsonb, TRUE, 'Freelance', 1
WHERE NOT EXISTS (SELECT 1 FROM experiences WHERE company = 'Freelance' AND title = 'Full Stack Developer');

INSERT INTO certificates (title, issuer, issue_date, credential_url, display_order)
SELECT 'Responsive Web Design', 'freeCodeCamp', '2024-06-01', 'https://www.freecodecamp.org/certification/vikasjagtap/responsive-web-design', 1
WHERE NOT EXISTS (SELECT 1 FROM certificates WHERE title = 'Responsive Web Design');

INSERT INTO certificates (title, issuer, issue_date, credential_url, display_order)
SELECT 'JavaScript Algorithms and Data Structures', 'freeCodeCamp', '2024-08-01', 'https://www.freecodecamp.org/certification/vikasjagtap/javascript-algorithms-and-data-structures', 2
WHERE NOT EXISTS (SELECT 1 FROM certificates WHERE title = 'JavaScript Algorithms and Data Structures');

INSERT INTO notification_settings (notification_email, send_confirmation_email)
SELECT 'vikasjagtap.9996@gmail.com', TRUE
WHERE NOT EXISTS (SELECT 1 FROM notification_settings);

INSERT INTO resume_settings (file_url, file_name)
SELECT '/uploads/resume.pdf', 'Vikas-Jagtap-Resume.pdf'
WHERE NOT EXISTS (SELECT 1 FROM resume_settings);
